/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example.pages;

import com.example.service.VehicleService;
import com.example.model.Vehicle;
import java.util.List;

/**
 *
 * @author ripsc
 */
public class DashboardPanel extends javax.swing.JPanel {
    private final VehicleService vehicleService = new VehicleService();
    
    private void loadKendaraan() {
        List<Vehicle> vehicles = vehicleService.getVehicles();
        int jumlahKendaraan = vehicles.size();

        valueCardJumlahKendaraan.setText(String.valueOf(jumlahKendaraan));
    }
    
    private void loadKendaraanMotor() {
        List<Vehicle> motorVehicles = vehicleService.getMotorVehicles();
        int jumlahMotor = motorVehicles.size();

        valueCardJumlahMotor.setText(String.valueOf(jumlahMotor));
    }
    
    private void loadKendaraanMobil() {
        List<Vehicle> mobilVehicles = vehicleService.getMotorVehicles();
        int jumlahMobil = mobilVehicles.size();

        valueCardJumlahMobil.setText(String.valueOf(jumlahMobil));
    }
    
    private void loadKendaraanAvailableMotor() {
        List<Vehicle> motorVehicles = vehicleService.getMotorAvailableVehicles();
        int jumlahMotor = motorVehicles.size();

        valueCardJumlahMotorTersedia.setText(String.valueOf(jumlahMotor));
    }
    
    private void loadKendaraanAvailableMobil() {
        List<Vehicle> mobilVehicles = vehicleService.getMobilAvailableVehicles();
        int jumlahMobil = mobilVehicles.size();

        valueCardJumlahMobilTersedia.setText(String.valueOf(jumlahMobil));
    }

    /**
     * Creates new form DashboardPanel
     */
    public DashboardPanel() {
        initComponents();
        loadKendaraan();
        loadKendaraanMotor();
        loadKendaraanMobil();
        List<Vehicle> motorAvailableVehicles = vehicleService.getMotorAvailableVehicles();
        int jumlahMotorAvailable = motorAvailableVehicles.size();
        List<Vehicle> mobilAvailableVehicles = vehicleService.getMobilAvailableVehicles();
        int jumlahMobilAvailable = mobilAvailableVehicles.size();
        
        int jumlahKendaraanTersedia = jumlahMotorAvailable + jumlahMobilAvailable;
        
        valueCardJumlahKendaraanTersedia.setText(String.valueOf(jumlahKendaraanTersedia));
        loadKendaraanAvailableMotor();
        loadKendaraanAvailableMobil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cardJumlahKendaraan = new javax.swing.JPanel();
        titleCardJumlahKendaraan = new javax.swing.JLabel();
        valueCardJumlahKendaraan = new javax.swing.JLabel();
        cardJumlahMotor = new javax.swing.JPanel();
        titleCardJumlahMotor = new javax.swing.JLabel();
        valueCardJumlahMotor = new javax.swing.JLabel();
        cardJumlahMobil = new javax.swing.JPanel();
        titleCardJumlahMobil = new javax.swing.JLabel();
        valueCardJumlahMobil = new javax.swing.JLabel();
        cardJumlahKendaraanTersedia = new javax.swing.JPanel();
        titleCardJumlahKendaraanTersedia = new javax.swing.JLabel();
        valueCardJumlahKendaraanTersedia = new javax.swing.JLabel();
        cardJumlahMotorTersedia = new javax.swing.JPanel();
        titleCardJumlahMotorTersedia = new javax.swing.JLabel();
        valueCardJumlahMotorTersedia = new javax.swing.JLabel();
        cardJumlahMobilTersedia = new javax.swing.JPanel();
        titleCardJumlahMobilTersedia = new javax.swing.JLabel();
        valueCardJumlahMobilTersedia = new javax.swing.JLabel();
        titleDashboard = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        cardJumlahKendaraan.setBackground(java.awt.Color.white);
        cardJumlahKendaraan.setBorder(new javax.swing.border.LineBorder(java.awt.Color.lightGray, 2, true));
        cardJumlahKendaraan.setMinimumSize(new java.awt.Dimension(120, 30));
        cardJumlahKendaraan.setPreferredSize(new java.awt.Dimension(160, 40));
        cardJumlahKendaraan.setLayout(new java.awt.GridBagLayout());

        titleCardJumlahKendaraan.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        titleCardJumlahKendaraan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleCardJumlahKendaraan.setText("Kendaraan");
        titleCardJumlahKendaraan.setMaximumSize(new java.awt.Dimension(1000, 28));
        titleCardJumlahKendaraan.setPreferredSize(new java.awt.Dimension(120, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        cardJumlahKendaraan.add(titleCardJumlahKendaraan, gridBagConstraints);

        valueCardJumlahKendaraan.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        valueCardJumlahKendaraan.setText("50");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        cardJumlahKendaraan.add(valueCardJumlahKendaraan, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 60;
        add(cardJumlahKendaraan, gridBagConstraints);

        cardJumlahMotor.setBackground(java.awt.Color.white);
        cardJumlahMotor.setBorder(new javax.swing.border.LineBorder(java.awt.Color.lightGray, 2, true));
        cardJumlahMotor.setMinimumSize(new java.awt.Dimension(120, 30));
        cardJumlahMotor.setPreferredSize(new java.awt.Dimension(160, 40));
        cardJumlahMotor.setLayout(new java.awt.GridBagLayout());

        titleCardJumlahMotor.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        titleCardJumlahMotor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleCardJumlahMotor.setText("Motor");
        titleCardJumlahMotor.setPreferredSize(new java.awt.Dimension(120, 28));
        cardJumlahMotor.add(titleCardJumlahMotor, new java.awt.GridBagConstraints());

        valueCardJumlahMotor.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        valueCardJumlahMotor.setText("50");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        cardJumlahMotor.add(valueCardJumlahMotor, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 60;
        add(cardJumlahMotor, gridBagConstraints);

        cardJumlahMobil.setBackground(java.awt.Color.white);
        cardJumlahMobil.setBorder(new javax.swing.border.LineBorder(java.awt.Color.lightGray, 2, true));
        cardJumlahMobil.setMinimumSize(new java.awt.Dimension(120, 30));
        cardJumlahMobil.setPreferredSize(new java.awt.Dimension(160, 40));
        cardJumlahMobil.setLayout(new java.awt.GridBagLayout());

        titleCardJumlahMobil.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        titleCardJumlahMobil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleCardJumlahMobil.setText("Mobil");
        titleCardJumlahMobil.setPreferredSize(new java.awt.Dimension(120, 28));
        cardJumlahMobil.add(titleCardJumlahMobil, new java.awt.GridBagConstraints());

        valueCardJumlahMobil.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        valueCardJumlahMobil.setText("50");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        cardJumlahMobil.add(valueCardJumlahMobil, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 60;
        add(cardJumlahMobil, gridBagConstraints);

        cardJumlahKendaraanTersedia.setBackground(java.awt.Color.white);
        cardJumlahKendaraanTersedia.setBorder(new javax.swing.border.LineBorder(java.awt.Color.lightGray, 2, true));
        cardJumlahKendaraanTersedia.setMinimumSize(new java.awt.Dimension(120, 30));
        cardJumlahKendaraanTersedia.setPreferredSize(new java.awt.Dimension(160, 40));
        cardJumlahKendaraanTersedia.setLayout(new java.awt.GridBagLayout());

        titleCardJumlahKendaraanTersedia.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        titleCardJumlahKendaraanTersedia.setText("Kendaraan Tersedia");
        cardJumlahKendaraanTersedia.add(titleCardJumlahKendaraanTersedia, new java.awt.GridBagConstraints());

        valueCardJumlahKendaraanTersedia.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        valueCardJumlahKendaraanTersedia.setText("50");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        cardJumlahKendaraanTersedia.add(valueCardJumlahKendaraanTersedia, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 60;
        add(cardJumlahKendaraanTersedia, gridBagConstraints);

        cardJumlahMotorTersedia.setBackground(java.awt.Color.white);
        cardJumlahMotorTersedia.setBorder(new javax.swing.border.LineBorder(java.awt.Color.lightGray, 2, true));
        cardJumlahMotorTersedia.setMinimumSize(new java.awt.Dimension(120, 30));
        cardJumlahMotorTersedia.setPreferredSize(new java.awt.Dimension(160, 40));
        cardJumlahMotorTersedia.setLayout(new java.awt.GridBagLayout());

        titleCardJumlahMotorTersedia.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        titleCardJumlahMotorTersedia.setText("Motor Tersedia");
        cardJumlahMotorTersedia.add(titleCardJumlahMotorTersedia, new java.awt.GridBagConstraints());

        valueCardJumlahMotorTersedia.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        valueCardJumlahMotorTersedia.setText("50");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        cardJumlahMotorTersedia.add(valueCardJumlahMotorTersedia, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 30, 30);
        add(cardJumlahMotorTersedia, gridBagConstraints);

        cardJumlahMobilTersedia.setBackground(java.awt.Color.white);
        cardJumlahMobilTersedia.setBorder(new javax.swing.border.LineBorder(java.awt.Color.lightGray, 2, true));
        cardJumlahMobilTersedia.setMinimumSize(new java.awt.Dimension(120, 30));
        cardJumlahMobilTersedia.setPreferredSize(new java.awt.Dimension(160, 40));
        cardJumlahMobilTersedia.setLayout(new java.awt.GridBagLayout());

        titleCardJumlahMobilTersedia.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        titleCardJumlahMobilTersedia.setText("Mobil Tersedia");
        cardJumlahMobilTersedia.add(titleCardJumlahMobilTersedia, new java.awt.GridBagConstraints());

        valueCardJumlahMobilTersedia.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        valueCardJumlahMobilTersedia.setText("50");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        cardJumlahMobilTersedia.add(valueCardJumlahMobilTersedia, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 60;
        add(cardJumlahMobilTersedia, gridBagConstraints);

        titleDashboard.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        titleDashboard.setText("Dashboard");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        add(titleDashboard, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardJumlahKendaraan;
    private javax.swing.JPanel cardJumlahKendaraanTersedia;
    private javax.swing.JPanel cardJumlahMobil;
    private javax.swing.JPanel cardJumlahMobilTersedia;
    private javax.swing.JPanel cardJumlahMotor;
    private javax.swing.JPanel cardJumlahMotorTersedia;
    private javax.swing.JLabel titleCardJumlahKendaraan;
    private javax.swing.JLabel titleCardJumlahKendaraanTersedia;
    private javax.swing.JLabel titleCardJumlahMobil;
    private javax.swing.JLabel titleCardJumlahMobilTersedia;
    private javax.swing.JLabel titleCardJumlahMotor;
    private javax.swing.JLabel titleCardJumlahMotorTersedia;
    private javax.swing.JLabel titleDashboard;
    private javax.swing.JLabel valueCardJumlahKendaraan;
    private javax.swing.JLabel valueCardJumlahKendaraanTersedia;
    private javax.swing.JLabel valueCardJumlahMobil;
    private javax.swing.JLabel valueCardJumlahMobilTersedia;
    private javax.swing.JLabel valueCardJumlahMotor;
    private javax.swing.JLabel valueCardJumlahMotorTersedia;
    // End of variables declaration//GEN-END:variables
}
