/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.pages;

import com.example.model.User;
import com.example.utils.CustomResult;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import com.example.service.UserService;
import com.example.utils.Hash;

/**
 *
 * @author ripsc
 */
public class PelangganRegisterFrame extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public PelangganRegisterFrame() {
        initComponents();
        
        setTitle("Register | Aplikasi Sewa Kendaraan");
//        setSize(414, 393); // Ukuran default
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        
        // Nonaktifkan resize
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        formPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        usernameInput = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordInput = new javax.swing.JPasswordField();
        registerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        redirectRegister = new javax.swing.JLabel();
        passwordLabel1 = new javax.swing.JLabel();
        konfirmasiPasswordInput = new javax.swing.JPasswordField();
        nikInput = new javax.swing.JTextField();
        usernameLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        formPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 50, 50, 50));
        formPanel.setLayout(new java.awt.GridBagLayout());

        title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        title.setText("Register");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        formPanel.add(title, gridBagConstraints);

        usernameLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        usernameLabel.setLabelFor(usernameInput);
        usernameLabel.setText("Username :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        formPanel.add(usernameLabel, gridBagConstraints);

        usernameInput.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        usernameInput.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        usernameInput.setToolTipText("Please input username");
        usernameInput.setMinimumSize(new java.awt.Dimension(64, 30));
        usernameInput.setPreferredSize(new java.awt.Dimension(64, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        formPanel.add(usernameInput, gridBagConstraints);

        passwordLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        passwordLabel.setLabelFor(passwordInput);
        passwordLabel.setText("Password :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        formPanel.add(passwordLabel, gridBagConstraints);

        passwordInput.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        passwordInput.setToolTipText("Please enter password");
        passwordInput.setMinimumSize(new java.awt.Dimension(64, 30));
        passwordInput.setPreferredSize(new java.awt.Dimension(64, 30));
        passwordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordInputActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        formPanel.add(passwordInput, gridBagConstraints);

        registerButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        registerButton.setText("Register");
        registerButton.setMaximumSize(new java.awt.Dimension(74, 30));
        registerButton.setMinimumSize(new java.awt.Dimension(74, 30));
        registerButton.setPreferredSize(new java.awt.Dimension(75, 30));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        formPanel.add(registerButton, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Sudah memiliki akun ?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        formPanel.add(jLabel1, gridBagConstraints);

        redirectRegister.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        redirectRegister.setForeground(new java.awt.Color(0, 0, 255));
        redirectRegister.setText("Klik disini");
        redirectRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        redirectRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redirectRegisterMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 11;
        formPanel.add(redirectRegister, gridBagConstraints);

        passwordLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        passwordLabel1.setLabelFor(passwordInput);
        passwordLabel1.setText("Konfirmasi Password :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        formPanel.add(passwordLabel1, gridBagConstraints);

        konfirmasiPasswordInput.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        konfirmasiPasswordInput.setToolTipText("Please enter password");
        konfirmasiPasswordInput.setMinimumSize(new java.awt.Dimension(64, 30));
        konfirmasiPasswordInput.setPreferredSize(new java.awt.Dimension(64, 30));
        konfirmasiPasswordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konfirmasiPasswordInputActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        formPanel.add(konfirmasiPasswordInput, gridBagConstraints);

        nikInput.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nikInput.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nikInput.setToolTipText("Please input username");
        nikInput.setMinimumSize(new java.awt.Dimension(64, 30));
        nikInput.setPreferredSize(new java.awt.Dimension(64, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        formPanel.add(nikInput, gridBagConstraints);

        usernameLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        usernameLabel1.setLabelFor(usernameInput);
        usernameLabel1.setText("NIK");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        formPanel.add(usernameLabel1, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordInputActionPerformed

    private void konfirmasiPasswordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konfirmasiPasswordInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_konfirmasiPasswordInputActionPerformed

    private void redirectRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redirectRegisterMouseClicked
        this.setVisible(false);
        
        PelangganLoginFrame pelangganLoginFrame = new PelangganLoginFrame();
        pelangganLoginFrame.setVisible(true);
        
        pelangganLoginFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                PelangganRegisterFrame.this.setVisible(true);
            }
        });
    }//GEN-LAST:event_redirectRegisterMouseClicked

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        String nikValue = nikInput.getText();
        String usernameValue = usernameInput.getText();
        String passwordValue = new String(passwordInput.getPassword());
        String konfirmasiPasswordValue = new String(konfirmasiPasswordInput.getPassword());
        
        if (nikValue.isEmpty()) {
            JOptionPane.showMessageDialog(null, "NIK harus diisi", "Oops", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (usernameValue.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Username harus diisi", "Oops", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (passwordValue.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Password harus diisi", "Oops", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (konfirmasiPasswordValue.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Konfirmasi Password harus diisi", "Oops", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (!passwordValue.equals(konfirmasiPasswordValue)) {
            JOptionPane.showMessageDialog(null, "Konfirmasi Password tidak sesuai", "Oops", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String passwordHashed = Hash.hashPassword(passwordValue);
        
        User newUser = new User();
        newUser.setNik(nikValue);
        newUser.setUsernane(usernameValue);
        newUser.setPassword(passwordHashed);
        newUser.setRole("pelanggan");

        UserService userService = new UserService();
        CustomResult result = userService.createUser(newUser);
        if (result.isSuccess()) {
            JOptionPane.showMessageDialog(this, result.getMessage());
            HomePelangganFrame homePelangganFrame = new HomePelangganFrame();
            this.setVisible(false);
            homePelangganFrame.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, result.getMessage(), "Oops", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PelangganRegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PelangganRegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PelangganRegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PelangganRegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PelangganRegisterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField konfirmasiPasswordInput;
    private javax.swing.JTextField nikInput;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel passwordLabel1;
    private javax.swing.JLabel redirectRegister;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel title;
    private javax.swing.JTextField usernameInput;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameLabel1;
    // End of variables declaration//GEN-END:variables
}
